### ISSUE TITLE
Heart system doesn't work on 1.21 (PaperMC)

### ISSUE THREAD

**Issue by marcjoancr** [cometcake575/Origins-Reborn#7]

**Comment by cometcake575** [comment]
What version of the plugin are you on and what specific abilities don't seem to be working? I've recently done some development involving the heart system (though the update has not yet been released) on 1.21 and have experienced no issues. Are you getting any errors in the console?

**Comment by compinerd** [comment]
dunno if its connected but with the magicorigins:kill_boost taking fall damage an error message appears in the console, seemingly due to some rounding errors.

However the player's UI always shows him to have 10 hearts, no matter if he's at 1 or 30 hp, without the perks the ui works as intended.


here's whats displayed in the console:
```
[00:26:03 WARN]: [Origins-Fantasy] Task #8586108 for Origins-Fantasy v1.0.23 generated an exception
java.lang.IllegalArgumentException: Health value (28.059999465942383) must be between 0 and 28.0. (attribute base value: 20.0, player: Robin)
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:483) ~[guava-33.3.1-jre.jar:?]
        at org.bukkit.craftbukkit.entity.CraftLivingEntity.setHealth(CraftLivingEntity.java:112) ~[paper-1.21.4.jar:1.21.4-71-83995d7e]
        at Origins-Magic-1.0.6-all.jar/com.starshootercity.magicorigins.abilities.KillBoost.lambda$setAbsorption$0(KillBoost.java:73) ~[Origins-Magic-1.0.6-all.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:78) ~[paper-1.21.4.jar:1.21.4-71-83995d7e]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:474) ~[paper-1.21.4.jar:1.21.4-71-83995d7e]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1659) ~[paper-1.21.4.jar:1.21.4-71-83995d7e]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1529) ~[paper-1.21.4.jar:1.21.4-71-83995d7e]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1251) ~[paper-1.21.4.jar:1.21.4-71-83995d7e]
        at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:310) ~[paper-1.21.4.jar:1.21.4-71-83995d7e]
        at java.base/java.lang.Thread.run(Thread.java:1575) ~[?:?]
```
